# archivo de configuraci칩n para GitHub Actions
# nombre del workflow
name: DevOpsJoseMarquez25

# controles cuando el workflow corra
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout repo
        uses: actions/checkout@v4

      # Verificar que el archivo HTML existe
      - name: Verificar archivos
        run: ls -la

      # Simulaci칩n de build (CI)
      - name: Validaci칩n CI
        run: echo "CI ejecutado correctamente"

      # Despliegue autom치tico a GitHub Pages
      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
